### ISSUE TITLE
Fechar convidado, tema e data do ep004

### ISSUE THREAD

**Issue by pullrecast-dev** [pullrecast-dev/pullrecast-dev.github.io#6]
para semana de 3 a 7 de outubro

**Comment by pullrecast-dev** [comment]
opa, adiantando com Yara do TDC, qual dia/hora mesmo?

**Comment by matbiit** [comment]
07/10 16h30
Yara Mascarenhas
👩🏽‍💻 CEO [@thedevconf](https://www.instagram.com/thedevconf/) fundadora [@falearena](https://www.instagram.com/falearena/)
https://www.instagram.com/yara.tdc/
👩🏽‍🎓Computação ICMC/USP
#womanintech #openinnovation #community
www.thedevconf.com
https://www.linkedin.com/in/yaramascarenhas/
